spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /sysinternals
    
server:
  shutdown: graceful
  port: 8443
  ssl:
    key-store: classpath:keystore/RadiusManager.p12
    key-store-type: PKCS12
    key-store-password: c4l1346926
    key-alias: RadiusManager



