spring:
  profiles:
    active:
  datasource:
    url: "jdbc:mysql://localhost:3306/RadiusManager"
    username: "rmapp"
    password: "rmapp123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
logging:
  config: config/log4j2.xml
  level:
    spring: info
    ar: debug

  
