spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/RadiusManager"
    username: "rmapp"
    password: "rmapp123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  messages:
    basename: i18n/messages
    encoding: UTF-8
  
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /sysinternals
  endpoint:
    health:
      show-details: always
    
server:
  shutdown: graceful
  port: 8443
  ssl:
    key-store: classpath:keystore/RadiusManager.p12
    key-store-type: PKCS12
    key-store-password: c4l1346926
    key-alias: RadiusManager

logging:
  config: config/log4j2.xml
  level:
    spring: info
    ar: debug

nas:
  port: 3799
suspended-users:
  rate-limit: "1024k/1024k"
accounting-paging:
  page-size: 10


