spring:
  datasource:
    url: "jdbc:mysql://170.231.179.246:3306/RadiusManager"
    username: "rmapp"
    password: "rmapp123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
  resources:
    static-locations: classpath:/static/

logging:
  config: config/log4j2.xml
  level:
    org: fatal
    ar: info

management:
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN

nas:
  port: 3799
  
suspended-users:
  apply-rate-limit: true
  rate-limit: "1024k/1024k"
  
accounting-paging:
  page-size: 10
clientslist-paging:
  page-size: 10
