spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
  resources:
    static-locations: classpath:/static/

logging:
  level:
    spring: warn
    ar: info

management:
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
